### ISSUE TITLE
After LubeLogger is updated, it reverts to US language file

### ISSUE THREAD

**Issue by myharries** [hargata/lubelog_translations#27]
Issuie: After LubeLogger is updated, it reverts to US language file.
This may only be because I am uploading a language file locally, as the en_AU file I have put a pull request has not been accepted yet?

**Comment by hargata** [comment]
no, that shouldn't be a problem, are you running it on Docker? It was brought to my attention recently that some times users have outdated docker-compose.yml which results in their translations volume not persisting.

**Comment by myharries** [comment]
Hi, Yes, it is running through a docker, on an UnRaid server.
This has happened on each of the last few updates.
I have to upload the json file, again.
I tried adding it to your translation files, but I'm not sure I did it correctly ;-(
As for the docker-compose.yml being outdated, I'm not sure what that is?

**Comment by hargata** [comment]
@myharries so the docker-compose file specifies the volumes that LubeLogger requires to persist, you should have a volume that points to `/App/wwwroot/translations` this will prevent the translation files from being cleared out everytime you update.

**Comment by Fabeuss** [comment]
Great, it works! Thanks for the tip.
It should be added to the documentation for non-English speaking users.
