### ISSUE TITLE
Locale not changing

### ISSUE THREAD

**Issue by ParadoxLeon** [hargata/lubelog_translations#35]
Hi,
I want to change the locale to `de_DE.UTF8`
But when I set `LC_LANG:` and `LANG:` in the `appsettings.json` nothing changes.
I also downloaded the `DE.json` and uploaded it.

Am I missing something?

**Comment by hargata** [comment]
If you're using the Docker image, locale is NOT set via appsettings.json, instead it is configured via the .env file or by passing in an environment variable directly into the container, also note that you will have to docker-compose up after that.

https://docs.lubelogger.com/Troubleshooting#locale-issues

**Comment by ParadoxLeon** [comment]
I'm using the windows executable.
Sorry forgot to mention this:)

**Comment by hargata** [comment]
@ParadoxLeon if you're using the Windows executable, the locale is based on your Windows settings. i.e. if your Windows region is set to Germany then LubeLogger will automatically derive its date and currency format from Windows.

**Comment by ParadoxLeon** [comment]
Thanks :) 

Setting the regional formatting to German solved this problem.
