### ISSUE TITLE
Easier way to translate?

### ISSUE THREAD

**Issue by thehijacker** [hargata/lubelog_translations#59]
I love translating to my native language and have translated many applications that I use often. And Lubelogger is the most painful so far to translate. I need to sync repo, prettify english JSON, sort by alphanumeric and then compare with my old Slovenian translation.

And that is exactly what I have done just now, but I can see many strings that were before in en_GB.json and are no longer there and it is just a big mess.

Can I please ask for you to move translations to web pages like crowdin or weblate? That integrate with github to pull translated files and I am sure json as a translation file is fully supported. That would make things much much easier.

Thank you,

**Comment by hargata** [comment]
You're going to like the next release,

In the next release, root users will have access to a built in translation editor, you can modify the text and then save the translation without exiting the app.

To contribute to the git repo, you can export the translation file

See it in action:

![buildintranslationeditor](https://github.com/user-attachments/assets/34ccc3da-31a9-4e3c-a409-7134ab4ac966)

**Comment by thehijacker** [comment]
This looks great. Will wait for next release then. Thank you.

**Comment by hargata** [comment]
This is now released, if you encounter an error, it's because of a very small bug detailed with workaround [here](https://github.com/hargata/lubelog/pull/681)

But shouldn't be an issue since you'd already have translations uploaded previously.

There is also a feature not shown in my original gif that I uploaded, where it will allow you to download translations.

![translationdownloader](https://github.com/user-attachments/assets/441bbf2e-84d8-4a63-aa8a-f9afafba208a)

**Comment by thehijacker** [comment]
> This is now released, if you encounter an error, it's because of a very small bug detailed with workaround [here](https://github.com/hargata/lubelog/pull/681)
> 
> But shouldn't be an issue since you'd already have translations uploaded previously.
> 
> There is also a feature not shown in my original gif that I uploaded, where it will allow you to download translations.
> 
> ![translationdownloader](https://private-user-images.githubusercontent.com/155338622/382113952-441bbf2e-84d8-4a63-aa8a-f9afafba208a.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA0MTI3NDMsIm5iZiI6MTczMDQxMjQ0MywicGF0aCI6Ii8xNTUzMzg2MjIvMzgyMTEzOTUyLTQ0MWJiZjJlLTg0ZDgtNGE2My1hYThhLWY5YWZhZmJhMjA4YS5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAzMVQyMjA3MjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZTE3MGEzOTZmYmIwNjlkMzM1NjM1YWNlNDJmYWRjYjkxZGI1NDdiZWRlYzBiNjFiNzAwYTM2M2I3NGUzNWU2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.uZiahBuhz2V0vvfnkXw1D-mw1vaOIA_GRZZSwMUYtn4) [ ![translationdownloader](https://private-user-images.githubusercontent.com/155338622/382113952-441bbf2e-84d8-4a63-aa8a-f9afafba208a.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA0MTI3NDMsIm5iZiI6MTczMDQxMjQ0MywicGF0aCI6Ii8xNTUzMzg2MjIvMzgyMTEzOTUyLTQ0MWJiZjJlLTg0ZDgtNGE2My1hYThhLWY5YWZhZmJhMjA4YS5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAzMVQyMjA3MjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZTE3MGEzOTZmYmIwNjlkMzM1NjM1YWNlNDJmYWRjYjkxZGI1NDdiZWRlYzBiNjFiNzAwYTM2M2I3NGUzNWU2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.uZiahBuhz2V0vvfnkXw1D-mw1vaOIA_GRZZSwMUYtn4) ](https://private-user-images.githubusercontent.com/155338622/382113952-441bbf2e-84d8-4a63-aa8a-f9afafba208a.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA0MTI3NDMsIm5iZiI6MTczMDQxMjQ0MywicGF0aCI6Ii8xNTUzMzg2MjIvMzgyMTEzOTUyLTQ0MWJiZjJlLTg0ZDgtNGE2My1hYThhLWY5YWZhZmJhMjA4YS5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAzMVQyMjA3MjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZTE3MGEzOTZmYmIwNjlkMzM1NjM1YWNlNDJmYWRjYjkxZGI1NDdiZWRlYzBiNjFiNzAwYTM2M2I3NGUzNWU2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.uZiahBuhz2V0vvfnkXw1D-mw1vaOIA_GRZZSwMUYtn4) [ ](https://private-user-images.githubusercontent.com/155338622/382113952-441bbf2e-84d8-4a63-aa8a-f9afafba208a.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA0MTI3NDMsIm5iZiI6MTczMDQxMjQ0MywicGF0aCI6Ii8xNTUzMzg2MjIvMzgyMTEzOTUyLTQ0MWJiZjJlLTg0ZDgtNGE2My1hYThhLWY5YWZhZmJhMjA4YS5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAzMVQyMjA3MjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZTE3MGEzOTZmYmIwNjlkMzM1NjM1YWNlNDJmYWRjYjkxZGI1NDdiZWRlYzBiNjFiNzAwYTM2M2I3NGUzNWU2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.uZiahBuhz2V0vvfnkXw1D-mw1vaOIA_GRZZSwMUYtn4)

Thank you very much! Already made a PR with updated translation.
